### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by 1N50MN14** [teifip/gcic-mqtt-client#1]
@teifip do you happen to know if this runs in a browser environment / IoT Core allows for that?

**Comment by teifip** [comment]
@1N50MN14 - This simple helper is designed entirely for Node.js. The target use case is to run it on quite powerful IoT devices (Raspberry Pi 3) that need Node.js for other parts of the application. However, the [MQTT.js](https://www.npmjs.com/package/mqtt) library used as foundation can be run in the browser. Therefore, it should be possible for you to start from that, and simply add the code specific to the use with [Google Cloud IoT Core](https://cloud.google.com/iot-core/). Depending on your requirements, you may want to note that [Google Cloud IoT Core](https://cloud.google.com/iot-core/) also supports an **HTTP bridge** as an alternative to the **MQTT bridge** (see a high-level comparison [here](https://cloud.google.com/iot/docs/concepts/protocols)). Maybe the **HTTP bridge** can be a better fit for your browser-based client.
